### ISSUE TITLE
Controller Startup Failures

### ISSUE THREAD

**Issue by itaouil** [graiola/wolf-setup#1]
Ciao Gennaro :),

Thanks for open sourcing this work.

I am thinking to use your package as a way to make AlienGo climb stairs by integrating it with a planner.

I was trying to run the wbc in simulation by following the instructions in your README (through a system installation), but when I launch the package I obtain the following error:

![error](https://user-images.githubusercontent.com/17275225/141615643-20c2c25c-9b58-4e2e-8b23-28a37066ce93.png)

But the **controller_plugin.xml** seems to be exported in the **package.xml**. Am I missing something?

Best,
Ilyass

**Comment by graiola** [comment]
Hi @itaouil, it seems that a debian package was not correctly installed or sourced. Can you check if you have the debian wbc-setup/debs/bionic/advr/cartesian_interface-2.0.0-6d1e2e1-amd64-bionic.deb correctly installed? Also, do you have git-lfs?

**Comment by itaouil** [comment]
Hi,

Thanks for the prompt reply.

The debian package **cartesian_interface-2.0.0-6d1e2e1-amd64-bionic.deb** is present in the **wbc-setup** workspace.

And yes, I made sure to install **git-lfs**.

It actually installs the WBC debian packages, although it throws some warnings:

![image](https://user-images.githubusercontent.com/17275225/141642577-1ef7eafe-8f6d-4174-af38-eaccc3ff4c28.png)

And similarly for the ADVR debian packages:

![image](https://user-images.githubusercontent.com/17275225/141642592-52875c5a-5e4a-4c76-810c-7164f5ff22d5.png)

**Comment by graiola** [comment]
Can you roscd cartesian_interface?

**Comment by itaouil** [comment]
No.

I tried and there is no such package installed.

![image](https://user-images.githubusercontent.com/17275225/141647631-63530634-11f7-4615-b72e-d0aa166bbd08.png)

**Comment by graiola** [comment]
Can you confirm that the pkg is installed with dpkg -l | grep cartesian_interface? Also, could you try echo $ROS_PACKAGE_PATH ?

Thank you!

**Comment by itaouil** [comment]
The output of **dpkg -l | grep cartesian_interface**:

![image](https://user-images.githubusercontent.com/17275225/141647821-57f01dcb-4420-4999-9c4c-3fdb63c9548b.png)

The output of **$ROS_PACKAGE_PATH**:

![image](https://user-images.githubusercontent.com/17275225/141647873-98a6b02f-deb0-4aa7-a9f8-3b3210507604.png)

**Comment by graiola** [comment]
It looks like the xbot distro is not being sourced... try in a new terminal to run `source /opt/xbot/setup.bash` and then launch the wb_controller `roslaunch wb_controller wb_controller_bringup.launch`

**Comment by itaouil** [comment]
Yes. Sourcing the xbot setup fixed the issue :).

Thanks for you prompt replies and help.

**Comment by itaouil** [comment]
Hi @graiola,

In the latest push I think you might have forgot to include something while generation the debs:

![image](https://user-images.githubusercontent.com/17275225/144417921-1c8f6f95-c9d8-4ccd-939e-ed3f4188dab9.png)

**Comment by graiola** [comment]
Sorry, I should generate the debians in a docker container instead I am using my computer which sometimes has developments going on... I generated the new debians. Sorry for the inconvenience.

**Comment by itaouil** [comment]
No problem at all :).

Thank you!

**Comment by itaouil** [comment]
Problem seems to be still present :)

![image](https://user-images.githubusercontent.com/17275225/144455373-bd887801-26e1-49fb-a315-566f31a3dd15.png)

**Comment by graiola** [comment]
Give me few minutes...

**Comment by graiola** [comment]
Give it a try :)

**Comment by itaouil** [comment]
Error still present :)

![image](https://user-images.githubusercontent.com/17275225/144462329-5f0749fd-ee79-4905-b60f-3593400e337b.png)

**Comment by graiola** [comment]
Ok so I guess my environment is dirty... I would suggest you to use the old debian for the moment... I am going to work on it in the next hours

**Comment by graiola** [comment]
I just updated the debian again... hopefully it works this time :)

**Comment by itaouil** [comment]
Thanks for the push Gennaro.

While trying to install I receive this:

![image](https://user-images.githubusercontent.com/17275225/144561459-e55f958f-afe4-4573-89b3-06014537e3f0.png)

Before I try to downgrade the xbotinterface I want to make sure this is the right step? :)

**Comment by graiola** [comment]
I just tested the current configuration in the docker image, and it seems to work fine :)

but there is the new XBotInterface debian on git to download.

anyway our plan is to move the debians out of git in the next days to make the download process simpler

**Comment by itaouil** [comment]
Yes. The docker image works fine.

The docker works fine, but I think the wrong **xbotinterface** was used when you generated the debs for the system installation maybe?

Anyway, I will use the new push with the docker for the moment :)

**Comment by itaouil** [comment]
Yes. The docker image works fine :).

There still seems to be some issues with the system install, but I will stick to using the docker image for the moment:

![image](https://user-images.githubusercontent.com/17275225/144625734-97410ba4-9127-42eb-87c8-9ffe107abb38.png)

**Comment by graiola** [comment]
Hi @itaouil , we updated the way the debians are stored, now they are on dropbox. If you want, you can try to download the debians with install_dependencies.sh or get_debians.sh. Also, we removed git-lfs and purged the debians from the repo.

If you can give it a try it would be super helpful :)

Thank you!

**Comment by itaouil** [comment]
Great!

I'll give it a try in a few hours :)

**Comment by itaouil** [comment]
Hi,

Nice re-branding haha. I like the wolf part :).

The docker image works fine. Regarding this, where can I add a new world (under wb_gazebo_resources?) and a new aliengo model (I want to add a sensor plugin to it to have also some perception in the simulator along with the WBC)?

Regarding the system installation, I encountered some errors in the installation process:

1) 

**Even when a run the script with sudo**

![image](https://user-images.githubusercontent.com/17275225/144702254-42a7a62d-867f-4fd9-bc04-da3c24a4c698.png)

which I guess leads to this error:

2) 
![image](https://user-images.githubusercontent.com/17275225/144702272-764b1769-43e2-4ccb-a394-736d2feb26c1.png)


I tried to manually install the package by running **sudo su** and install the xbot env manually. but when I try that:

![image](https://user-images.githubusercontent.com/17275225/144703456-d007dcf4-f377-4fb6-82fa-70f49b8b67fa.png)

**Comment by graiola** [comment]
Hi @itaouil, thank you for the feedback :)

are you using `install_dependencies.sh` to install the debians or do you do it manually?

Regarding the gazebo model: you can add your new model to the `$GAZEBO_MODEL_PATH`, then it should show up when you launch gazebo.
If you are using the docker, you can load your local ros workspace with the model in it with the option `run_docker.sh --local your_ros_ws`, but the container will not have the  `$GAZEBO_MODEL_PATH` updated. You could try to modify line 15 in `fun.cfg` with:

`-e GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/melodic/share/wb_gazebo_resources/models/`

so that the container gets your modified `$GAZEBO_MODEL_PATH`

if it works you can open a PR :)

Regarding the robot model, you can work in a similar way: just put everything in your local ros workspace and run the docker container with the local option. The way the robots are loaded is the following:
There are an `upload.launch` and `world.launch` in `wb_controller/launch` that are called when the controller is spawned. These two launch files are responsible for loading the `robot_description` and `robot_semantic_description` on the ros param server which are the `urdf` and `srdf` files of the robot. So, technically you could imitate what I do with a robot `urdf` and `srdf` (for examples look at `aliengo_description/robots`) and load the new robot with `roslaunch wb_controller wb_controller_bringup robot_name:=new_robot`.
Be careful that you will need also a set of params for the robot (look at `wb_controller/params` to get an idea).

I am going to move the robot params into each respective robot to simplify the loading :)

**Comment by itaouil** [comment]
Hi @graiola,

Thanks for the info.

Yes, I am using the script to install the dependencies.

The problem is similar to the one shown in the [link](https://askubuntu.com/questions/1328914/how-to-give-apt-user-permission-to-var-lib-apt-lists/1328915#1328915). I tried to change to permissions before the **install.sh** script is run but with no luck so far.

Also, I noticed that you removed the  **XbotInterface-2.0.0** and now rely only on **XbotInterface-2.1.0**, but the xbot msgs is still at version 2.0.0, while xbot_env at version 1.0.0, could this be related to this error?

![image](https://user-images.githubusercontent.com/17275225/144717846-f3b69891-6586-4fcd-9a26-da80d479fa77.png)

**Comment by itaouil** [comment]
Ok.

I managed to install it by **--force-overwrite** the installation of the packages, but then:

![image](https://user-images.githubusercontent.com/17275225/144718477-5c9b9d10-2846-42e7-a751-5a55e16170ef.png)

![image](https://user-images.githubusercontent.com/17275225/144718488-454862ae-f5ef-41a1-9aa5-13eea742b4fd.png)

**Comment by graiola** [comment]
In the `debs/advr` folder, there is `uninstall.sh`, can you run it? and then run `install.sh`

**Comment by graiola** [comment]
> ![image](https://user-images.githubusercontent.com/17275225/144718488-454862ae-f5ef-41a1-9aa5-13eea742b4fd.png)

ahaha why there are two robots? :):)

**Comment by itaouil** [comment]
> In the `debs/advr` folder, there is `uninstall.sh`, can you run it? and then run `install.sh`

![image](https://user-images.githubusercontent.com/17275225/144718541-a524b934-020b-46fc-9f13-5a41f2ba870d.png)

**Comment by graiola** [comment]
> > In the `debs/advr` folder, there is `uninstall.sh`, can you run it? and then run `install.sh`
> 
> ![image](https://user-images.githubusercontent.com/17275225/144718541-a524b934-020b-46fc-9f13-5a41f2ba870d.png)

it looks like a problem with _apt:

Give a look [here](https://newbedev.com/what-does-this-apt-error-message-download-is-performed-unsandboxed-as-root-mean)

**Comment by itaouil** [comment]
> > > In the `debs/advr` folder, there is `uninstall.sh`, can you run it? and then run `install.sh`
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17275225/144718541-a524b934-020b-46fc-9f13-5a41f2ba870d.png)
> 
> it looks like a problem with _apt:
> 
> Give a look [here](https://newbedev.com/what-does-this-apt-error-message-download-is-performed-unsandboxed-as-root-mean)

Adding these two lines 

```
sudo chown -Rv _apt:root $SCRIPTPATH/debs/$UBUNTU/advr/
sudo chmod -Rv 700 $SCRIPTPATH/debs/$UBUNTU/advr/
```

after the **get_debians.sh** call in the **install.sh** script fixes the installation error, but the two robot error spawn persists haha:

![image](https://user-images.githubusercontent.com/17275225/144718819-097dc9fe-977e-4807-b92f-8b22c863d3ba.png)

![image](https://user-images.githubusercontent.com/17275225/144718834-332c8048-0755-4ac4-8327-3b904481c707.png)

**Comment by graiola** [comment]
how are you running everything? In the docker, outside?

**Comment by itaouil** [comment]
No no the docker is fine, and works great.

All these errors are for the system installation only.

**Comment by graiola** [comment]
what if you spawn spot? `robot_name:=spot`

**Comment by graiola** [comment]
> The docker image works fine. Regarding this, where can I add a new world (under wb_gazebo_resources?) and a new aliengo model (I want to add a sensor plugin to it to have also some perception in the simulator along with the WBC)?
> 

I pushed the modification in `run_docker.sh` about the `$GAZEBO_MODEL_PATH`, feel free to try it

**Comment by itaouil** [comment]
> > > > In the `debs/advr` folder, there is `uninstall.sh`, can you run it? and then run `install.sh`
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/17275225/144718541-a524b934-020b-46fc-9f13-5a41f2ba870d.png)
> > 
> > 
> > it looks like a problem with _apt:
> > Give a look [here](https://newbedev.com/what-does-this-apt-error-message-download-is-performed-unsandboxed-as-root-mean)
> 
> Adding these two lines
> 
> ```
> sudo chown -Rv _apt:root $SCRIPTPATH/debs/$UBUNTU/advr/
> sudo chmod -Rv 700 $SCRIPTPATH/debs/$UBUNTU/advr/
> ```
> 
> after the **get_debians.sh** call in the **install.sh** script fixes the installation error, but the two robot error spawn persists haha:
> 
> ![image](https://user-images.githubusercontent.com/17275225/144718819-097dc9fe-977e-4807-b92f-8b22c863d3ba.png)
> 
> ![image](https://user-images.githubusercontent.com/17275225/144718834-332c8048-0755-4ac4-8327-3b904481c707.png)

This is what made the controller fail for me in the system installation process:

```
source ~/workspace/code/larvio_gpu/ros_wrapper/devel/setup.bashsource /opt/xbot/setup.bash
```

The sourcing command for **xbot** was added in the same line as the last one and not in a new one by the **install_dependencies.sh** script. Once I added an extra newline all worked fine for the system installation too.

**Comment by graiola** [comment]
That's weird because I explicitly append `/opt/xbot/setup.bash` in the bashrc... https://github.com/graiola/wolf-setup/blob/master/install_dependencies.sh#L62

Anyway, I am glad that the issue is fixed now.

Do you still have the problem with the two robots spawning?

**Comment by itaouil** [comment]
No everything works fine now :). No double robots party anymore.

**Comment by itaouil** [comment]
Hi :),

I changed the name of this issue so it accounts for all errors related to starting the controller.

In the last push the **wolf_description_utils** are not included so it cannot load the models:

![image](https://user-images.githubusercontent.com/17275225/145598956-b44c7ff0-f5d0-42bc-a592-53bd6d10920a.png)

Thought to let you know in case you missed it :)

P.S: If you might want to be notified about this sort of stuff via a different channel or by opening a new issue whenever the error is different. Let me know :)

**Comment by graiola** [comment]
I just added the debian :)

to speedup the communication we could use another channel too... suggestions?

**Comment by itaouil** [comment]
Yes. Now it works :).

Possible platforms could be:

- Telegram
- Slack
- Discord
- Mattermost

These are the ones that pop in my mind atm.
